export enum SCENES {
  INTRO = 'INTRO',
  MAP = 'MAP',
  MAIN_MISSION = 'MAIN_MISSION',
  SUB_MISSION = 'SUB_MISSION',
  OTHER_MISSION = 'OTHER_MISSION',
  TREASURE_HUNT_MISSIONS = 'TREASURE_HUNT_MISSIONS',
  FINALE = 'FINALE'
}
